apiVersion: apps/v1
kind: Deployment
metadata:
  name: globeco-allocation-service
  labels:
    app: globeco-allocation-service
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globeco-allocation-service
  template:
    metadata:
      labels:
        app: globeco-allocation-service
    spec:
      containers:
      - name: allocation-service
        image: kasbench/globeco-allocation-service-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8089
          name: http
        envFrom:
        - configMapRef:
            name: allocation-service-config-dev
        # env:
        # - name: DATABASE_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: allocation-service-secrets
        #       key: database-password
        volumeMounts:
        - name: globeco-allocation-service-shared-files
          mountPath: /usr/local/share/files
        - name: tmp
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            memory: "2000Mi"
            cpu: "2000m"
          limits:
            memory: "2000Mi"
            cpu: "2000m"
        # volumeMounts:
        # - name: tmp-files
        #   mountPath: /tmp/files
      volumes:
      - name: globeco-allocation-service-shared-files
        persistentVolumeClaim:
          claimName: globeco-allocation-service-shared-files-pvc
      - name: tmp
        emptyDir:
          sizeLimit: 1Gi
      
      