apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: globeco-allocation-service-shared-files-pvc
  labels:
    app: globeco-allocation-service
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
