apiVersion: v1
kind: Service
metadata:
  name: globeco-allocation-service
  labels:
    app: globeco-allocation-service
    environment: development
spec:
  type: ClusterIP
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
    name: http
  selector:
    app: globeco-allocation-service