apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-files-pvc
  labels:
    app: globeco-allocation-service
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---
# High-performance storage for production
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-files-pvc-prod
  labels:
    app: globeco-allocation-service
    component: storage
    environment: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd
  # Additional requirements for production
  volumeMode: Filesystem
---
# Development storage with smaller size
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-files-pvc-dev
  labels:
    app: globeco-allocation-service
    component: storage
    environment: development
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
# Storage Class definitions (to be applied if not already present)
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: fast-ssd
#   labels:
#     app: globeco-allocation-service
# provisioner: kubernetes.io/gce-pd  # Adjust based on cloud provider
# parameters:
#   type: pd-ssd
#   replication-type: regional-pd
#   zones: us-central1-a,us-central1-b
# allowVolumeExpansion: true
# reclaimPolicy: Retain
# volumeBindingMode: WaitForFirstConsumer 