apiVersion: v1
kind: Secret
metadata:
  name: allocation-service-secrets
  labels:
    app: globeco-allocation-service
type: Opaque
data:
  # Base64 encoded values (these should be replaced with actual values in production)
  # For demo purposes: 'postgres123' -> cG9zdGdyZXMxMjM=
  database-password: cG9zdGdyZXMxMjM=
  
  # For production, generate strong passwords and encode them:
  # echo -n 'your-secure-password' | base64
  
  # Example: JWT signing key for future auth implementation
  # jwt-signing-key: <base64-encoded-jwt-key>
  
  # Example: External service API keys
  # trade-service-api-key: <base64-encoded-api-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: allocation-service-tls
  labels:
    app: globeco-allocation-service
type: kubernetes.io/tls
data:
  # TLS certificate and key for HTTPS (replace with actual values in production)
  # tls.crt: <base64-encoded-certificate>
  # tls.key: <base64-encoded-private-key>
  
  # For demo purposes, these are empty - would be populated by cert-manager in production
  tls.crt: ""
  tls.key: "" 